import Head from "next/head";
import Masthead from "../components/masthead";
import AboutUs from "@/components/aboutus";
import Skills from "@/components/skills";
import Works from "@/components/works";
import TrustedBy from "@/components/trustedby";
import ContactUs from "@/components/contactus";
import Footer from "@/components/footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>NailsWithShady</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Masthead />
      <AboutUs />
      <Skills />
      <Works />
      <TrustedBy />
      <ContactUs />
      <Footer />
    </div>
  );
}
